function [train_X, train_y, val_X, val_y, trainSize, valSize] = split_data(trainval_X, trainval_y)
% n_trainval = 20;
% [trainval_X,trainval_y] = generate_train_data(n_trainval);
[n, d]=size(trainval_X);
a = floor(n/4);            % how many people are in each grade section
b = floor(floor(n/4)/5); % 80 percent of this number will have to go 
trainSize = 4*(a-b);      % in train_, the rest in val_
valSize = a-b;


for j = 0:4;
    
 train_X((trainSize*j)+1:trainSize*(j+1),:) = [trainval_X((1:j*b),:);...
         trainval_X((((j+1)*b)+1):a,:); trainval_X((1:j*b)+a,:) ;...
         trainval_X(((((j+1)*b)+1):a)+a,:); trainval_X((1:j*b)+2*a,:) ;...
         trainval_X(((((j+1)*b)+1):a)+2*a,:); trainval_X((1:j*b)+3*a,:);...
         trainval_X(((((j+1)*b)+1):a)+3*a,:)];
 train_y((trainSize*j)+1:trainSize*(j+1),1) = [trainval_y((1:j*b),1);...
         trainval_y((((j+1)*b)+1):a,1); trainval_y((1:j*b)+a,1) ;...
         trainval_y(((((j+1)*b)+1):a)+a,1); trainval_y((1:j*b)+2*a,1) ;...
         trainval_y(((((j+1)*b)+1):a)+2*a,1); trainval_y((1:j*b)+3*a,1);...
         trainval_y(((((j+1)*b)+1):a)+3*a,1)];
 val_X((valSize*j)+1:valSize*(j+1),:) = [trainval_X((j*b+1):((j+1)*b),:); ...
         trainval_X(((j*b+1):((j+1)*b))+a,:); ...
         trainval_X(((j*b+1):((j+1)*b))+2*a,:); ...
         trainval_X(((j*b+1):((j+1)*b))+3*a,:)];
 val_y((valSize*j)+1:valSize*(j+1),1) = [trainval_y((j*b+1):((j+1)*b),1); ...
         trainval_y(((j*b+1):((j+1)*b))+a,1); ...
         trainval_y(((j*b+1):((j+1)*b))+2*a,1); ...
         trainval_y(((j*b+1):((j+1)*b))+3*a,1)];
end
